{% set name = "shexjsg" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 750016fabdb5487b27e2e714145f3602cd3ac4eb0dd9b7d7751d0cde62c0d1d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pbr
    - pip
  run:
    - python >={{ python_min }}
    - pyjsg >=0.11.10
    - rdflib

test:
  imports:
    - ShExJSG
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hsolbrig/ShExJSG
  summary: ShExJSG - Astract Syntax Tree for the ShEx 2.0 language
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jfy133
