{% set name = "shexjsg" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ShExJSG-{{ version }}.tar.gz
  sha256: f17a629fc577fa344382bdee143cd9ff86588537f9f811f66cea6f63cdbcd0b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pbr
    - pip
  run:
    - python >={{ python_min }}
    - pyjsg >=0.11.10
    - rdflib

test:
  imports:
    - ShExJSG
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hsolbrig/ShExJSG
  summary: ShExJSG - Astract Syntax Tree for the ShEx 2.0 language
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jfy133
